variables:
  AzureSubscription: 'Klaim Test&Dev'
  ServerName: 'ss-ias-uks-neilm.database.windows.net'
  DatabaseName: 'dbs-s03-uks-test-1'
  AdminUser: 'globaladmin'
  AdminPassword: 'SQL_Admin1!'
  SQLFile: 'script.sql'

steps:
- task: AzurePowerShell@2
  displayName: Azure PowerShell script - build.yaml
  inputs:
    azureSubscription: '$(AzureSubscription)'
    ScriptPath: '$(Build.SourcesDirectory)\scripts\SetAzureFirewallRule.ps1'
    ScriptArguments: '$(ServerName)'
    azurePowerShellVersion: LatestVersion

- task: CmdLine@1
  displayName: Run Sqlcmd
  inputs:
    filename: Sqlcmd
    arguments: '-S $(ServerName) -U $(AdminUser) -P $(AdminPassword) -d $(DatabaseName) -i $(SQLFile)'

- task: AzurePowerShell@2
  displayName: Azure PowerShell script - build.yaml
  inputs:
    azureSubscription: '$(AzureSubscription)'
    ScriptPath: '$(Build.SourcesDirectory)\scripts\RemoveAzureFirewallRule.ps1'
    ScriptArguments: '$(ServerName)'
    azurePowerShellVersion: LatestVersion
