variables:
  AzureSubscription: 'KCA2 Azure Test&Dev (S03)'
  ServerName: 'ss-ias-uks-neilm.database.windows.net'
  DatabaseName: 'dbs-s03-uks-test-1'
  AdminUser: 'globaladmin'
  AdminPassword: 'SQL_Admin1!'
  SQLFile: 'script.sql'

steps:
- task: CmdLine@1
  displayName: Run Sqlcmd
  inputs:
    filename: Sqlcmd
    arguments: '-S $(ServerName) -U $(AdminUser) -P $(AdminPassword) -d $(DatabaseName) -i $(SQLFile)'


