variables:
  AzureSubscription: 'KCA2 Azure Test&Dev (S03)'
  ServerName: 'ss-ias-uks-neilm.database.windows.net'
  DatabaseName: 'dbs-s03-uks-test-1'
  AdminUser: 'globaladmin'
  AdminPassword: 'SQL_Admin1!'
  DACPACFile: 'azure_sqltest.dacpac'

steps:
  - task: AzurePowerShell@2
    displayName: Azure PowerShell script: FilePath
    inputs:
      azureSubscription: '$(AzureSubscription)'
      ScriptPath: '$(Build.SourcesDirectory)\scripts\SetAzureFirewallRule.ps1'
      ScriptArguments: '$(ServerName)'
      azurePowerShellVersion: LatestVersion

  - task: SqlAzureDacpacDeployment@1
    displayName: Execute Azure SQL - DacpacTask
    inputs:
      azureSubscription: '$(AzureSubscription)'
      ServerName: '$(ServerName)'
      DatabaseName: '$(DatabaseName)'
      SqlUsername: '$(AdminUser)'
      SqlPassword: '-P $(AdminPassword)'
      DacpacFile: '$(DACPACFile)'

  - task: AzurePowerShell@2
    displayName: Azure PowerShell script: FilePath
    inputs:
      azureSubscription: '$(AzureSubscription)'
      ScriptPath: '$(Build.SourcesDirectory)\scripts\RemoveAzureFirewallRule.ps1'
      ScriptArguments: '$(ServerName)'
      azurePowerShellVersion: LatestVersion

